apiVersion: v1
kind: Secret
metadata:
  name: egs-secrets
type: Opaque
stringData:
  INTERNAL_SERVICE_KEY: internal-dev-key-2024
  INVENTORY_API_KEY: sk_test_inventory_dev_key
  PAYMENT_API_KEY: admin-dev-key-2024
  PAYMENT_ADMIN_API_KEY: admin-dev-key-2024
  AUTH_SECRET_KEY: super-secret-jwt-key-for-dev-2024
  STRIPE_SECRET_KEY: sk_test_placeholder
  STRIPE_WEBHOOK_SECRET: whsec_placeholder
  VAULT_TOKEN: dev-root-token
  VAULT_DEV_ROOT_TOKEN_ID: dev-root-token
  GRAFANA_ADMIN_USER: admin
  GRAFANA_ADMIN_PASSWORD: admin

  AUTH_DATABASE_URL: postgresql://user:password@auth-postgres:5432/auth_db
  AUTH_POSTGRES_USER: user
  AUTH_POSTGRES_PASSWORD: password
  AUTH_POSTGRES_DB: auth_db

  PAYMENT_AUTH_SECRET_KEY: super-secret-jwt-key-for-dev-payment-2024
  PAYMENT_AUTH_DATABASE_URL: postgresql://user:password@payment-auth-postgres:5432/auth_db
  PAYMENT_AUTH_POSTGRES_USER: user
  PAYMENT_AUTH_POSTGRES_PASSWORD: password
  PAYMENT_AUTH_POSTGRES_DB: auth_db

  INVENTORY_DATABASE_URL: postgresql+asyncpg://inventory_user:inventory_pass@inv-postgres:5432/inventory_db_fresh
  INVENTORY_POSTGRES_USER: inventory_user
  INVENTORY_POSTGRES_PASSWORD: inventory_pass
  INVENTORY_POSTGRES_DB: inventory_db_fresh

  PAYMENT_DATABASE_URL: postgresql+asyncpg://payment_user:payment_pass@pay-postgres:5432/payment_db
  PAYMENT_POSTGRES_USER: payment_user
  PAYMENT_POSTGRES_PASSWORD: payment_pass
  PAYMENT_POSTGRES_DB: payment_db
