apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: egs-hosts
spec:
  ingressClassName: traefik
  rules:
    - host: composer.flashsale
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: composer
                port:
                  number: 8000
    - host: grupo2-egs.deti.ua.pt
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: composer
                port:
                  number: 8000
    - host: auth.flashsale
      http:
        paths:
          - path: /templates
            pathType: Prefix
            backend:
              service:
                name: auth-frontend
                port:
                  number: 80
          - path: /static
            pathType: Prefix
            backend:
              service:
                name: auth-frontend
                port:
                  number: 80
          - path: /
            pathType: Prefix
            backend:
              service:
                name: auth-service
                port:
                  number: 8000
    - host: payment-auth.flashsale
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: payment-auth-service
                port:
                  number: 8000
    - host: inventory.flashsale
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: inventory-service
                port:
                  number: 8000
    - host: payment.flashsale
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: payment-service
                port:
                  number: 8000
    - host: grafana.flashsale
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: grafana
                port:
                  number: 3000
    - host: jaeger.flashsale
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: jaeger
                port:
                  number: 16686
    - host: prometheus.flashsale
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: prometheus
                port:
                  number: 9090
    - host: vault.flashsale
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: vault
                port:
                  number: 8200
    - host: mail.flashsale
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: mailhog
                port:
                  number: 8025
